#!/usr/bin/env python3
import colorama
from colorama import init, Fore
import sys


def welcome():
    print(f'{Fore.WHITE}\nWelcome to cCalculator {Fore.RED} By SoftAddict & ShellBreak \n')
    calculate()


def calculate():
    operation = input('''
    Please type in the math operation you would like to complete:
    + for addition
    - for subtraction
    * for multiplication
    / for division
    ** for power
    % for modulo
    ''')

    try:
        number_1 = input(Fore.GREEN + 'Enter Your First Number: ' + Fore.WHITE)
        number_2 = input(Fore.GREEN + 'Enter Your Second Number: ' + Fore.WHITE)

        if '.' not in number_1:
            number_1 = int(number_1)
        else:
            number_1 = float(number_1)

        ##############################

        if '.' not in number_2:
            number_2 = int(number_2)
        else:
            number_2 = int(number_2)

        ##############################
        # Addition
        if operation == '+':
            print('{} + {} = '.format(number_1, number_2))
            print(number_1 + number_2)

        # Subtraction
        elif operation == '-':
            print('{} - {} = '.format(number_1, number_2))
            print(number_1 - number_2)
        # Multiplication
        elif operation == '*':
            print('{} * {} = '.format(number_1, number_2))
            print(number_1 * number_2)

        # Division
        elif operation == '/':
            print('{} / {} = '.format(number_1, number_2))
            print(number_1 / number_2)

    except ValueError:
        print(Fore.RED + "Oh No! That's not a Number Enter a Number Please" + Fore.WHITE)


def again():
    calc_again = input(Fore.YELLOW + 'Do you want to calculate again? Please Type Y for YES or N for No: ' + Fore.WHITE)
    if calc_again == 'Y' or calc_again == 'y':
        calculate()
    elif calc_again == 'N' or calc_again == 'n':
        print(Fore.BLUE + 'Sorry to See you go! Come Again' + Fore.WHITE)
        sys.exit(1)
    if calc_again.upper() == 'Y':
        calculate()
    elif calc_again.upper() == 'N':
        print('See you later.')
        sys.exit(1)
    else:
        again()


welcome()
again()
