#!/usr/bin/env python3
import colorama
from colorama import init, Fore
import sys


def welcome():
    print(f'{Fore.WHITE}\nWelcome to cCalculator {Fore.RED} By SoftAddict & ShellBreak')
    calculate()


def calculate():
    print(f'''{Fore.RED}
    Please type in the math operation you would like to complete:
    + for addition
    - for subtraction
    * for multiplication
    / for division
    ** for power
    % for modulo''')
    operation = input('Operation: ')

    operation_options = ['+', '-', '*', '/', '**', '%']
    if operation not in operation_options:
        print (f'\n{Fore.WHITE} Not an acceptable operator!')
        calculate()


    try:
        number_1 = input(Fore.GREEN + 'Enter Your First Number: ' + Fore.WHITE)
        number_2 = input(Fore.GREEN + 'Enter Your Second Number: ' + Fore.WHITE)

        if '.' not in number_1:
            number_1 = int(number_1)
        else:
            number_1 = float(number_1)

        ##############################

        if '.' not in number_2:
            number_2 = int(number_2)
        else:
            number_2 = int(number_2)

        ##############################
        # Addition
        if operation == '+':
            print('{} + {} = '.format(number_1, number_2))
            print(number_1 + number_2)

        # Subtraction
        elif operation == '-':
            print('{} - {} = '.format(number_1, number_2))
            print(number_1 - number_2)
        # Multiplication
        elif operation == '*':
            print('{} * {} = '.format(number_1, number_2))
            print(number_1 * number_2)

        # Division
        elif operation == '/':
            print('{} / {} = '.format(number_1, number_2))
            print(number_1 / number_2)

	# Powers
        elif operation == '**':
            print('{} ^ {} = '.format(number_1, number_2))
            print(number_1 ** number_2)

        # Modulo
        elif operation == '%':
            print('{} % {} = '.format(number_1, number_2))
            print(number_1 % number_2)

    except ValueError:
        print(Fore.RED + "Oh No! That's not a Number Enter a Number Please" + Fore.WHITE)


def again():
    yes_options = ['Y', 'y', 'yes', 'Yes', 'YES']
    no_options = ['N', 'n', 'no', 'No', 'NO']
    calc_again = input(Fore.YELLOW + 'Do you want to calculate again? (yes/no): ' + Fore.WHITE)
    if calc_again in yes_options:
        calculate()
    elif calc_again in no_options:
        print(Fore.BLUE + 'Sorry to See you go! Come Again' + Fore.WHITE)
        sys.exit(1)
    else:
        again()

welcome()
again()
